FROM python:3.13.7

WORKDIR /usr/src/app

COPY ./requirements.txt .

RUN pip install -i https://mirror-pypi.runflare.com/simple --no-cache-dir  --upgrade -r ./requirements.txt

# Copy app source
COPY ./ ./app
COPY ./alembic ./alembic
COPY ./alembic.ini ./alembic.ini
COPY ./.env ./.env

# CMD ["fastapi", "dev", "--host", "0.0.0.0", "--port", "8000"]