services:
  backend:
    build: 
     context: . 
     dockerfile: Dockerfile.dev
    container_name: backend
    environment:
      
      PROJECT_NAME: "FastAPI Base To_Do_List Project"
      VERSION: str = "1.0.0"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgresql://postgres:postgres@db:5432/appdb
      API_KEY: dev-key
      SECRET_KEY: str = "db6c54211e35dbbc8d9c2bfea563458d"
      ACCESS_TOKEN_EXPIRE_MINUTES: int = 30
      ACCESS_TOKEN_EXPIRE_DAYS: int = 7
      ALGORITHM: str = "HS256"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/usr/src/app/app
      - ./alembic:/usr/src/app/alembic
      - ./alembic.ini:/usr/src/app/alembic.ini
    command: >
      fastapi dev --host 0.0.0.0 --port 8000
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    ports:
      - "5432:5432"



