"""update users table

Revision ID: a5beb32ec72f
Revises: 49ae74acb02b
Create Date: 2025-10-15 18:25:07.034292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5beb32ec72f'
down_revision: Union[str, Sequence[str], None] = '49ae74acb02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'all_user_type', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type', sa.Enum(
            'ADMIN', 'USER', name='usertype'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_type')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('all_user_type', type_='foreignkey')

    # ### end Alembic commands ###
