"""add priority to task model

Revision ID: d82a416ffe11
Revises: 8f16176919ae
Create Date: 2025-10-19 15:26:26.974389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd82a416ffe11'
down_revision: Union[str, Sequence[str], None] = '8f16176919ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # my config
    priority_enum = postgresql.ENUM('URGENT', 'HIGH', 'NORMAL', 'LOW', name='priority_enum')
    priority_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'NORMAL', 'LOW', name='priority_enum'), nullable=False, server_default='NORMAL'))
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###
